"""empty message

Revision ID: 0634d62a3495
Revises: 62a1a0569578
Create Date: 2024-10-25 22:08:19.613539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0634d62a3495'
down_revision = '62a1a0569578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_identifier', sa.String(length=50), nullable=False),
    sa.Column('generated_password', sa.String(length=100), nullable=False),
    sa.Column('otp', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_identifier')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_auth')
    # ### end Alembic commands ###
