"""empty message

Revision ID: 12137196db91
Revises: c5e3de2f38c6
Create Date: 2024-10-14 21:58:00.233006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12137196db91'
down_revision = 'c5e3de2f38c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_verification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_verification', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
