"""empty message

Revision ID: 62a1a0569578
Revises: 3436b0e71dd8
Create Date: 2024-10-25 19:07:14.825676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62a1a0569578'
down_revision = '3436b0e71dd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_verification', schema=None) as batch_op:
        batch_op.alter_column('is_verified',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_verified',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_verified',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('pending_verification', schema=None) as batch_op:
        batch_op.alter_column('is_verified',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
