"""empty message

Revision ID: 7a2ab83c3aae
Revises: 91828f75859b
Create Date: 2024-10-20 17:19:36.648669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a2ab83c3aae'
down_revision = '91828f75859b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))
        batch_op.drop_column('appointment_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_date', sa.DATETIME(), nullable=False))
        batch_op.drop_column('date')

    # ### end Alembic commands ###
