"""empty message

Revision ID: 7c1ecf3de806
Revises: a6c5d87f40da
Create Date: 2024-10-18 20:52:21.391069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c1ecf3de806'
down_revision = 'a6c5d87f40da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_change_verification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used_email', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint('uq_used_email', ['used_email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_change_verification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('used_email')

    # ### end Alembic commands ###
