"""empty message

Revision ID: 8aa992245d2c
Revises: f9c24524b7ca
Create Date: 2024-10-19 14:51:44.092264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aa992245d2c'
down_revision = 'f9c24524b7ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('image')
        batch_op.drop_column('license_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('license_number', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
