"""empty message

Revision ID: 9c589e2378fc
Revises: 12137196db91
Create Date: 2024-10-14 22:22:48.818539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c589e2378fc'
down_revision = '12137196db91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_verification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_verification', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
