"""empty message

Revision ID: aed0545a8808
Revises: 67a99aac9a10
Create Date: 2024-10-19 18:04:11.897351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aed0545a8808'
down_revision = '67a99aac9a10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_verification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_verification', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
