"""empty message

Revision ID: cd3fe3484896
Revises: 0634d62a3495
Create Date: 2024-10-26 19:21:53.197172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd3fe3484896'
down_revision = '0634d62a3495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reporter_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('reported_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_reported_user_id', 'user', ['reported_user_id'], ['id'])
        batch_op.create_foreign_key('fk_reporter_id', 'user', ['reporter_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_reporter_id', type_='foreignkey')
        batch_op.drop_constraint('fk_reported_user_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('reported_user_id')
        batch_op.drop_column('reporter_id')

    # ### end Alembic commands ###
