"""empty message

Revision ID: f9c24524b7ca
Revises: 953a5ea1c11f
Create Date: 2024-10-19 14:22:39.028823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9c24524b7ca'
down_revision = '953a5ea1c11f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('license_number', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('therapist_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_therapist', 'user', ['therapist_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('therapist_id')
        batch_op.drop_column('license_number')
        batch_op.drop_column('image')

    # ### end Alembic commands ###
